### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by luckspt**
Move `gin.setMode` per https://stackoverflow.com/a/52830435/15863093

### CODE REVIEW

**Review by Massad — APPROVED** [review]
Yes it makes sense to be at the top 👍

**Comment by luckspt** [comment]
I tried changing this but couldn't find out how via github on the web and didn't feel like it needs a new PR.
Would like to let you know I forgot to load godotenv before using it

**Comment by Massad** [comment]
@luckspt I've added it and had some free time so I've added a custom validator and did some best practices and cleanups.

Check 35a367a86a1c0c6289f965f61af906a7df029f40

**Comment by lyrbet** [comment]
There is a problem here. `os.Getenv("ENV")` should be after `godotenv.Load`
```go
//Load the .env file
err := godotenv.Load(".env")
if err != nil {
    log.Fatal("error: failed to load the env file")
}

if os.Getenv("ENV") == "PRODUCTION" {
    gin.SetMode(gin.ReleaseMode)
}
```

**Comment by luckspt** [comment]
IIRC the order was corrected by 35a367a

**Pull request merged**
